# Generated by Django 3.0.1 on 2019-12-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_url', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
